# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musciUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 776)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 20, 112, 32))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 20, 271, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 50, 951, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.startbtn = QtWidgets.QPushButton(self.centralwidget)
        self.startbtn.setGeometry(QtCore.QRect(640, 20, 112, 32))
        self.startbtn.setObjectName("startbtn")
        self.lab_time = QtWidgets.QLabel(self.centralwidget)
        self.lab_time.setGeometry(QtCore.QRect(960, 410, 58, 16))
        self.lab_time.setObjectName("lab_time")
        self.lab_duration = QtWidgets.QLabel(self.centralwidget)
        self.lab_duration.setGeometry(QtCore.QRect(40, 400, 58, 16))
        self.lab_duration.setObjectName("lab_duration")
        self.show_lab = QtWidgets.QLabel(self.centralwidget)
        self.show_lab.setGeometry(QtCore.QRect(50, 520, 58, 16))
        self.show_lab.setObjectName("show_lab")
        self.show_tim_lab = QtWidgets.QLabel(self.centralwidget)
        self.show_tim_lab.setGeometry(QtCore.QRect(940, 550, 58, 16))
        self.show_tim_lab.setObjectName("show_tim_lab")
        self.slider_time = QtWidgets.QSlider(self.centralwidget)
        self.slider_time.setGeometry(QtCore.QRect(40, 400, 961, 22))
        self.slider_time.setOrientation(QtCore.Qt.Horizontal)
        self.slider_time.setObjectName("slider_time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "打开"))
        self.startbtn.setText(_translate("MainWindow", "播放"))
        self.lab_time.setText(_translate("MainWindow", "00:00"))
        self.lab_duration.setText(_translate("MainWindow", "00:00"))
        self.show_lab.setText(_translate("MainWindow", "TextLabel"))
        self.show_tim_lab.setText(_translate("MainWindow", "TextLabel"))
